In [1]:
import os
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [3]:
df = pd.read_csv('data/data.csv')
df.head(20)

,Unnamed: 0,_id,_bag_id,_timestamp,_topic,_type,header__stamp__sec,header__stamp__nanosec,header__frame_id,nov_header__message_name,nov_header__message_id,nov_header__message_type,nov_header__sequence_number,nov_header__time_status,nov_header__gps_week_number,nov_header__gps_week_milliseconds,nov_header__receiver_status,nov_header__idle_time,ins_status__status,pos_type__type,latitude,longitude,height,undulation,north_velocity,east_velocity,up_velocity,roll,pitch,azimuth,latitude_stdev,longitude_stdev,height_stdev,north_velocity_stdev,east_velocity_stdev,up_velocity_stdev,roll_stdev,pitch_stdev,azimuth_stdev,ext_sol_status__status,time_since_update
0,0,9f84e3cf-28a7-4f80-a7e2-f8c646b61a42,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948939045476497,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948939,45476497,gps,INSPVAX,1465,0,0,180,2288,201757000,33554432,27.0,3,56,59.814623,30.316313,19.928836,16.0,5.357457,-5.756573,-0.014775,-1.038960,-2.936809,313.012804,0.029462,0.015447,0.047535,0.008755,0.007193,0.007338,0.031252,0.031922,0.154432,167772371,0
1,1,aac20a4b-ddee-4f6f-9790-8e87d26795aa,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948940044314703,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948940,44314703,gps,INSPVAX,1465,0,0,180,2288,201758000,33554432,25.0,3,56,59.814673,30.316206,19.884685,16.0,5.722782,-6.212015,-0.071847,-1.180583,-3.046664,312.920301,0.029398,0.015606,0.047469,0.008746,0.007166,0.007619,0.031469,0.032021,0.155016,167772371,0
2,2,fa13835e-f367-4488-84b0-c7e75b4dd042,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948941050300748,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948941,50300748,gps,INSPVAX,1465,0,0,180,2288,201759000,33554432,25.0,3,56,59.814724,30.316096,19.862731,16.0,5.763407,-6.178288,0.013064,-0.927270,-3.045107,312.852065,0.029395,0.015821,0.047438,0.008845,0.007233,0.007798,0.031308,0.031908,0.155438,167772371,0
3,3,c5e21907-4aec-400e-963f-befceb0ef33c,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948942053861726,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948942,53861726,gps,INSPVAX,1465,0,0,180,2288,201760000,33554432,27.0,3,56,59.814778,30.315981,19.836854,16.0,6.157075,-6.656251,-0.053489,-0.622619,-2.839728,312.849635,0.029417,0.016005,0.047523,0.008918,0.007315,0.007909,0.031176,0.031873,0.155788,167772371,0
4,4,7511b715-a1a6-40ff-b9c3-4d9037fe4607,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948943076547124,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948943,76547124,gps,INSPVAX,1465,0,0,180,2288,201761000,33554432,26.0,3,56,59.814835,30.315859,19.775900,16.0,6.509562,-7.051186,-0.038796,-0.771100,-3.096548,312.819780,0.029401,0.016132,0.047577,0.008578,0.007031,0.007695,0.030584,0.031278,0.155258,167772371,0
5,5,97d5ade8-a16b-4738-bf90-c318b0b3ef19,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948944044588623,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948944,44588623,gps,INSPVAX,1465,0,0,180,2288,201762000,33554432,26.0,3,56,59.814895,30.315730,19.745529,16.0,6.830380,-7.418706,-0.057401,-0.696524,-2.994692,312.814689,0.029310,0.016178,0.047454,0.008538,0.007004,0.007575,0.030256,0.030987,0.155707,167772371,0
6,6,6e2c9b11-53e5-4b78-bb61-1048cd0f50b4,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948945045367210,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948945,45367210,gps,INSPVAX,1465,0,0,180,2288,201763000,33554432,26.5,3,56,59.814957,30.315595,19.679357,16.0,7.085801,-7.713057,-0.083374,-0.970332,-3.106968,312.710814,0.029264,0.016207,0.047397,0.008495,0.006954,0.007706,0.030404,0.031078,0.156093,167772371,0
7,7,261a183e-6fa8-4255-aa7c-6e5fb1d6743d,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948946045829711,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948946,45829711,gps,INSPVAX,1465,0,0,180,2288,201764000,33554432,26.5,3,56,59.815020,30.315457,19.639827,16.0,6.975123,-7.819461,-0.060023,-0.896774,-3.025404,312.260567,0.029209,0.016218,0.047309,0.008520,0.007031,0.007566,0.030931,0.031647,0.156642,167772371,0
8,8,2adaaa25-19b5-4255-92be-56c2adfcc7b7,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948947050846898,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948947,50846898,gps,INSPVAX,1465,0,0,180,2288,201765000,33554432,26.5,3,56,59.815083,30.315314,19.585123,16.0,6.941433,-8.320833,-0.055363,-0.901288,-3.092286,310.804085,0.029180,0.016203,0.047242,0.008740,0.007388,0.007633,0.032015,0.032734,0.157350,167772371,0
9,9,03c745d3-38fa-4db6-b2df-0feda7e5bc71,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948948045156788,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948948,45156788,gps,INSPVAX,1465,0,0,180,2288,201766000,33554432,28.5,3,56,59.815145,30.315161,19.515273,16.0,6.800800,-8.798033,-0.072963,-0.715995,-3.308494,308.637024,0.029149,0.016194,0.047203,0.008884,0.007365,0.007598,0.031999,0.032946,0.156736,167772371,0
10,10,3f13188f-9e18-479b-9ab3-29477afbefee,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948949043417624,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948949,43417624,gps,INSPVAX,1465,0,0,180,2288,201767000,33554432,27.5,3,56,59.815205,30.315002,19.453018,16.0,6.685619,-8.998344,-0.095587,-0.973244,-3.355995,306.974234,0.029141,0.016125,0.047150,0.008894,0.007359,0.007751,0.032137,0.033185,0.156887,167772371,0
11,11,7a72ab54-880e-47cc-857a-021e538bf52b,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948950044628618,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948950,44628618,gps,INSPVAX,1465,0,0,180,2288,201768000,33554432,27.5,3,56,59.815264,30.314841,19.347590,16.0,6.494215,-9.067551,-0.026294,-1.146896,-3.501190,306.172032,0.029105,0.015930,0.047089,0.008864,0.007323,0.007672,0.031588,0.032934,0.156871,167772371,0
12,12,f2f4ce56-e4a2-4f16-87fb-8744123d278a,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948951045451749,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948951,45451749,gps,INSPVAX,1465,0,0,180,2288,201769000,33554432,28.5,3,56,59.815323,30.314679,19.237452,16.0,6.645425,-8.984502,-0.146191,-1.997188,-3.494246,306.288862,0.029094,0.015681,0.047091,0.009201,0.007271,0.007725,0.030959,0.032461,0.157154,167772371,0
13,13,a8d938c6-64e7-4eb9-a6e7-ed6a98a6f77f,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948952053483294,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948952,53483294,gps,INSPVAX,1465,0,0,180,2288,201770000,33554432,27.5,3,56,59.815384,30.314523,19.120757,16.0,7.088539,-8.587745,-0.117441,-1.943534,-3.545716,308.745926,0.029217,0.015453,0.047110,0.009123,0.007066,0.007749,0.030485,0.031818,0.157090,167772371,0
14,14,79cd8440-dd71-40c6-8beb-3f504ee409b7,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948953049485759,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948953,49485759,gps,INSPVAX,1465,0,0,180,2288,201771000,33554432,27.5,3,56,59.815450,30.314374,19.034607,16.0,7.530794,-8.166069,-0.042888,-2.438709,-3.059627,311.864044,0.029394,0.015343,0.047176,0.009006,0.007201,0.007617,0.029886,0.030952,0.156976,167772371,0
15,15,1dd9e7f3-5b08-4fed-be30-798de0896c9a,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948954045033455,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948954,45033455,gps,INSPVAX,1465,0,0,180,2288,201772000,33554432,28.5,3,56,59.815519,30.314231,19.017775,16.0,7.705010,-7.941673,-0.026590,-1.236401,-3.244255,313.979914,0.029426,0.015372,0.047222,0.008881,0.007091,0.007593,0.029578,0.030405,0.154132,167772371,0
16,16,e488baa9-da4c-4502-965a-118cf560d615,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948955044765588,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948955,44765588,gps,INSPVAX,1465,0,0,180,2288,201773000,33554432,28.0,3,56,59.815589,30.314090,18.948024,16.0,7.817887,-7.863591,-0.026237,-0.915890,-3.352377,314.880221,0.029464,0.015565,0.047268,0.008828,0.007218,0.007758,0.031264,0.031843,0.151974,167772371,0
17,17,a1f13b29-81c3-4ac5-a1cf-f729de158c9e,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948956044671829,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948956,44671829,gps,INSPVAX,1465,0,0,180,2288,201774000,33554432,27.0,3,56,59.815659,30.313950,18.903806,16.0,7.826225,-7.898441,-0.063464,-1.055771,-3.220715,314.933713,0.029417,0.015766,0.047264,0.008810,0.007267,0.007721,0.031953,0.032571,0.152127,167772371,0
18,18,c3c1c877-2af0-4150-ad47-452cba007e7d,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948957045640606,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948957,45640606,gps,INSPVAX,1465,0,0,180,2288,201775000,33554432,27.0,3,56,59.815729,30.313809,18.859758,16.0,7.796105,-7.876365,0.015554,-1.137216,-3.131747,314.896660,0.029304,0.015889,0.047189,0.008855,0.007330,0.007577,0.032034,0.032759,0.152882,167772371,0
19,19,4ed24210-3c01-48de-a54b-ccae22767b32,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948958053235466,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948958,53235466,gps,INSPVAX,1465,0,0,180,2288,201776000,33554432,26.5,3,56,59.815799,30.313668,18.803472,16.0,7.736278,-7.952064,-0.074531,-1.356579,-3.350634,314.575451,0.029253,0.016048,0.047153,0.008895,0.007345,0.007513,0.031476,0.032309,0.153309,167772371,0

In [4]:
df[['_id', '_bag_id', '_timestamp', '_topic', '_type', 'header__stamp__sec', 'header__stamp__nanosec', 'header__frame_id', 'nov_header__message_name', 'nov_header__message_id', 'nov_header__message_type', 'nov_header__sequence_number', 'nov_header__time_status', 'nov_header__gps_week_number', 'nov_header__gps_week_milliseconds', 'nov_header__receiver_status', 'nov_header__idle_time', 'latitude', 'longitude', 'height', 'north_velocity', 'east_velocity', 'up_velocity', 'roll', 'pitch', 'azimuth', 'pos_type__type']]

,_id,_bag_id,_timestamp,_topic,_type,header__stamp__sec,header__stamp__nanosec,header__frame_id,nov_header__message_name,nov_header__message_id,nov_header__message_type,nov_header__sequence_number,nov_header__time_status,nov_header__gps_week_number,nov_header__gps_week_milliseconds,nov_header__receiver_status,nov_header__idle_time,latitude,longitude,height,north_velocity,east_velocity,up_velocity,roll,pitch,azimuth,pos_type__type
0,9f84e3cf-28a7-4f80-a7e2-f8c646b61a42,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948939045476497,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948939,45476497,gps,INSPVAX,1465,0,0,180,2288,201757000,33554432,27.0,59.814623,30.316313,19.928836,5.357457,-5.756573,-0.014775,-1.038960,-2.936809,313.012804,56
1,aac20a4b-ddee-4f6f-9790-8e87d26795aa,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948940044314703,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948940,44314703,gps,INSPVAX,1465,0,0,180,2288,201758000,33554432,25.0,59.814673,30.316206,19.884685,5.722782,-6.212015,-0.071847,-1.180583,-3.046664,312.920301,56
2,fa13835e-f367-4488-84b0-c7e75b4dd042,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948941050300748,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948941,50300748,gps,INSPVAX,1465,0,0,180,2288,201759000,33554432,25.0,59.814724,30.316096,19.862731,5.763407,-6.178288,0.013064,-0.927270,-3.045107,312.852065,56
3,c5e21907-4aec-400e-963f-befceb0ef33c,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948942053861726,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948942,53861726,gps,INSPVAX,1465,0,0,180,2288,201760000,33554432,27.0,59.814778,30.315981,19.836854,6.157075,-6.656251,-0.053489,-0.622619,-2.839728,312.849635,56
4,7511b715-a1a6-40ff-b9c3-4d9037fe4607,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699948943076547124,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699948943,76547124,gps,INSPVAX,1465,0,0,180,2288,201761000,33554432,26.0,59.814835,30.315859,19.775900,6.509562,-7.051186,-0.038796,-0.771100,-3.096548,312.819780,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8122,98c67b9b-7524-49c0-96c8-d56a8de43596,8e6f6408-705b-4680-828a-77ae16097d1c,1699959681075656140,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959681,75656140,gps,INSPVAX,1465,0,0,180,2288,212499000,33587200,27.5,59.774619,30.360762,27.599042,-0.001198,-0.006112,0.004307,1.493880,-2.598446,336.044819,56
8123,ac53340c-f848-413a-9a80-de8c25432160,8e6f6408-705b-4680-828a-77ae16097d1c,1699959682092646442,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959682,92646442,gps,INSPVAX,1465,0,0,180,2288,212500000,33587200,30.0,59.774619,30.360762,27.592180,0.003703,-0.001435,0.000187,1.477588,-2.718914,336.042289,56
8124,7e046752-3453-4d58-8853-5e1b666d19b0,8e6f6408-705b-4680-828a-77ae16097d1c,1699959683060925179,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959683,60925179,gps,INSPVAX,1465,0,0,180,2288,212501000,33587200,28.0,59.774619,30.360762,27.595149,0.001083,0.002094,0.002580,1.470420,-2.707953,336.046549,56
8125,9558fc7f-68b1-45bc-bb20-2efd7f8682bc,8e6f6408-705b-4680-828a-77ae16097d1c,1699959684054907940,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959684,54907940,gps,INSPVAX,1465,0,0,180,2288,212502000,33587200,28.0,59.774619,30.360762,27.592634,-0.000469,0.002442,0.000319,1.467469,-2.704795,336.033679,56
8126,527c1b85-f7ac-4e6c-8613-e34b3e08c193,8e6f6408-705b-4680-828a-77ae16097d1c,1699959685053043497,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959685,53043497,gps,INSPVAX,1465,0,0,180,2288,212503000,33587200,30.0,59.774619,30.360762,27.591513,0.001913,0.003714,-0.004373,1.524635,-2.709968,336.070155,56

In [5]:
df[df['pos_type__type'] == 19]

,Unnamed: 0,_id,_bag_id,_timestamp,_topic,_type,header__stamp__sec,header__stamp__nanosec,header__frame_id,nov_header__message_name,nov_header__message_id,nov_header__message_type,nov_header__sequence_number,nov_header__time_status,nov_header__gps_week_number,nov_header__gps_week_milliseconds,nov_header__receiver_status,nov_header__idle_time,ins_status__status,pos_type__type,latitude,longitude,height,undulation,north_velocity,east_velocity,up_velocity,roll,pitch,azimuth,latitude_stdev,longitude_stdev,height_stdev,north_velocity_stdev,east_velocity_stdev,up_velocity_stdev,roll_stdev,pitch_stdev,azimuth_stdev,ext_sol_status__status,time_since_update
269,269,9ae11eab-e321-4004-893b-3c78cebbb2d2,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699949208050798836,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699949208,50798836,gps,INSPVAX,1465,0,0,180,2288,202026000,33554432,30.5,6,19,59.832042,30.288462,15.106966,16.0,9.653762,-3.743048,-0.040623,-2.887045,-3.562528,338.930814,0.079611,0.068327,0.099515,0.033064,0.029996,0.015115,0.041479,0.042704,0.140840,167772224,0
272,272,ed3906f4-820f-4e7b-95f3-63d8c0543124,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699949211040502372,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699949211,40502372,gps,INSPVAX,1465,0,0,180,2288,202029000,33554432,29.5,3,19,59.832282,30.288275,15.015408,16.0,8.011381,-3.617637,-0.081090,-2.010528,-3.455169,337.320877,0.345442,0.357030,0.317559,0.054383,0.050798,0.020775,0.052157,0.053199,0.146585,167772354,0
273,273,02218823-2662-496a-a19d-514b711be2bf,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699949212052020780,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699949212,52020780,gps,INSPVAX,1465,0,0,180,2288,202030000,33554432,31.5,3,19,59.832350,30.288205,14.989892,16.0,7.215024,-4.269351,0.000381,-1.945833,-3.399719,332.419408,0.425097,0.445036,0.371988,0.062288,0.058541,0.022639,0.054994,0.055984,0.148365,167776448,0
274,274,e9cc466e-d0ba-4eb0-b6d8-a5a372542376,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699949213043804428,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699949213,43804428,gps,INSPVAX,1465,0,0,180,2288,202031000,33554432,30.5,6,19,59.832411,30.288123,14.970924,16.0,6.470720,-5.061090,-0.026099,-1.791101,-3.183854,325.805723,0.587342,0.625637,0.503332,0.070720,0.066894,0.024521,0.057738,0.058662,0.150177,167772224,0
275,275,211d4551-1b6a-4bf5-9fb7-4add7f69c259,8941a4d9-2ec5-e763-1729-7aa4d329b06a,1699949214048355780,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699949214,48355780,gps,INSPVAX,1465,0,0,180,2288,202032000,33554432,30.5,6,19,59.832466,30.288024,14.947467,16.0,5.789488,-5.947409,-0.049958,-1.789183,-3.038005,318.044358,0.741662,0.796859,0.622090,0.077884,0.068763,0.026392,0.057584,0.060136,0.151976,167772224,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8007,8007,f1ad2b3b-7fd9-4393-8a57-a39023bfa659,8e6f6408-705b-4680-828a-77ae16097d1c,1699959566042646189,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959566,42646189,gps,INSPVAX,1465,0,0,180,2288,212384000,33554432,39.5,6,19,59.760843,30.381347,27.233112,16.0,12.026019,-17.157682,-0.073175,1.646572,-2.980947,304.807631,0.138477,0.127951,0.138819,0.057455,0.055998,0.028420,0.077717,0.078193,0.230996,167772224,0
8008,8008,095cf1be-dfa8-4a2c-868c-66506b5c6e3d,8e6f6408-705b-4680-828a-77ae16097d1c,1699959567057422428,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959567,57422428,gps,INSPVAX,1465,0,0,180,2288,212385000,33554432,36.0,6,19,59.760950,30.381044,27.110605,16.0,11.958951,-16.931462,0.002561,1.776012,-2.855195,305.065289,0.138477,0.127951,0.138819,0.057455,0.055998,0.028420,0.077717,0.078193,0.230996,167772224,0
8009,8009,df270e41-dc83-4c3c-9259-f5e085157f0f,8e6f6408-705b-4680-828a-77ae16097d1c,1699959568052757672,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959568,52757672,gps,INSPVAX,1465,0,0,180,2288,212386000,33554432,36.0,6,19,59.761058,30.380745,27.053661,16.0,11.965466,-16.602724,-0.048500,1.636832,-2.959648,305.535128,0.234530,0.227537,0.221660,0.078961,0.077333,0.030334,0.079826,0.080344,0.233775,167772224,0
8093,8093,6f9000e8-cf97-4d5f-9235-baccba135a65,8e6f6408-705b-4680-828a-77ae16097d1c,1699959652046878497,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959652,46878497,gps,INSPVAX,1465,0,0,180,2288,212470000,33554432,24.5,6,19,59.773067,30.362130,26.921648,16.0,11.962508,-5.529184,0.029353,1.666374,-2.938751,335.125443,0.045644,0.033893,0.069492,0.020810,0.019105,0.013449,0.051272,0.050364,0.192609,167772224,0
8094,8094,6549398e-569c-40e8-95a2-fa7b0bcdb2a1,8e6f6408-705b-4680-828a-77ae16097d1c,1699959653047366749,/gnss/novatel/oem7/inspvax,novatel_oem7_msgs/msg/INSPVAX,1699959653,47366749,gps,INSPVAX,1465,0,0,180,2288,212471000,33587200,26.0,6,19,59.773174,30.362033,26.943054,16.0,11.807928,-5.394029,0.011645,1.456703,-2.909172,335.377307,0.070604,0.058218,0.095620,0.026644,0.024849,0.015430,0.053486,0.052598,0.194075,167772224,0

In [6]:
df[['latitude', 'longitude']]

       latitude  longitude
0     59.814623  30.316313
1     59.814673  30.316206
2     59.814724  30.316096
3     59.814778  30.315981
4     59.814835  30.315859
...         ...        ...
8122  59.774619  30.360762
8123  59.774619  30.360762
8124  59.774619  30.360762
8125  59.774619  30.360762
8126  59.774619  30.360762

[8127 rows x 2 columns]